### ISSUE TITLE
Question: missing openshift ca bundle?

### ISSUE THREAD

**Issue by frzifus** [os-observability/redhat-rhosdt-samples#15]
In otel multitenant example, we use the default ca bundle.
https://github.com/os-observability/redhat-rhosdt-samples/blob/7d6b8a5a79376bea09ba740be3adb8bda018f384/opentelemetry/multitenant/otelcol.yaml#L124

Do we not need the openshift ca`s?

**Example**
```yaml
apiVersion: template.openshift.io/v1
kind: Template
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      namespace: ${NAMESPACE}
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
      name: otelcol-cabundle
  - apiVersion: opentelemetry.io/v1alpha1
    kind: OpenTelemetryCollector
    spec:
      volumeMounts:
        - mountPath: /etc/pki/ca-trust/source/service-ca
          name: cabundle-volume
      volumes:
        - configMap:
            name: otelcol-cabundle
          name: cabundle-volume
      config: |
...
          otlp:
            endpoint: observatorium-tempostack.${NAMESPACE}.svc.cluster.local:8090
            tls:
              insecure: false
              ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
...
```

cc @iblancasa
